### ISSUE TITLE
error while running install_github("CSOIreland/csodata")

### ISSUE THREAD

**Issue by Gwilhermines** [CSOIreland/csodata#2]
Hello,

I am going the following error when trying to install from git.

All the best.

Best regards,

─  preparing 'csodata':
✔  checking DESCRIPTION meta-information ... 
E  checking vignette meta-information ... 
   Output(s) listed in 'build/vignette.rds' but not in package:
     'inst/doc/quick_start_guide.html'
   Run R CMD build without --no-build-vignettes to re-create
Error: Failed to install 'csodata' from GitHub:
  ! System command 'Rcmd.exe' failed
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers

**Comment by Conor-Crowley** [comment]
Try installing from the development branch and let me know if this fixes your issue.
----
devtools::install_github("CSOIreland/csodata@1.3.0")

**Comment by Gwilhermines** [comment]
Main branch works now. Thank You!
