### ISSUE TITLE
Very slow response from data.cso.ie

### ISSUE THREAD

**Issue by stainesa** [CSOIreland/csodata#21]
Hi,
Using the latest cran csodata 1.4.2
Observed - request frequently times out with error message ' "Warning: Failed retrieving table of contents. Please check internet connection and that data.cso.ie is online"
Loaded cached data'

This is despite cso.data.ie being open in my browser, and the internet connection working well.
Eventually it will respond, but it can take several tries.

**Comment by Conor-Crowley** [comment]
Hey Anthony,
Slow performance is often related to the cache.
Try setting cache = FALSE.
For example; cso_get_data("FE001", cache = FALSE)
Let me know if you see any improvement.
regards,

Conor

**Comment by stainesa** [comment]
Will give it a whirl!
thanks,
AS

**Comment by stainesa** [comment]
Much much faster - thank you!
