### ISSUE TITLE
csodata removed from CRAN

### ISSUE THREAD

**Issue by semanticnoodles** [CSOIreland/csodata#8]
Hello,
I am pretty sure you are aware of the situation [https://cran-archive.r-project.org/web/checks/2022/2022-07-19_check_results_csodata.html](https://cran-archive.r-project.org/web/checks/2022/2022-07-19_check_results_csodata.html) - just checking in.

**Comment by Conor-Crowley** [comment]
Yes we should be back up on CRAN before too long.

**Comment by jamesor19** [comment]
Hi @semanticnoodles , the package is back up on CRAN as of today.
